package engine

import (
	"bytes"
	"regexp"
)

var noticeLine = regexp.MustCompile(notice)

// EmptyPolicy defines the policy to apply when a generated file is empty.
//
// By default, the policy is set to PolicyRemove,
// meaning that a generated file will be removed if it is empty
// or contains only the notice "Code generated by [\w\-\/]+; DO NOT EDIT.".
type EmptyPolicy int

const (
	// PolicyKeep will keep the file if it exists and is empty.
	PolicyKeep EmptyPolicy = iota + 1

	// PolicyRemove will remove the file if it exists and is empty.
	//
	// This is the default behavior.
	PolicyRemove
)

// IsEmpty returns true if the given content is considered empty according to the provided policy.
//
// A file is expected to be removed if:
//   - it's empty
//   - it contains only the generated notice
//   - the policy is set to Keep
//
// Note: lines with the generated notice are completely stripped.
// In case of additional comments, keep them out of the generated notice line.
func IsEmpty(content []byte, policy EmptyPolicy) bool {
	if policy == PolicyKeep {
		return false
	}
	for line := range bytes.Lines(content) {
		if len(bytes.TrimSpace(line)) == 0 || noticeLine.Match(line) {
			continue
		}

		// trim only the regexp \s class, a line with a Unicode space around its delimiter isn't empty
		trimmed := bytes.Trim(line, " \t\n\f\r")
		switch string(trimmed) {
		case "/*", "*/", "<!--", "-->":
		default:
			if !bytes.HasPrefix(trimmed, []byte("#!")) {
				return false
			}
		}
	}
	return true
}
