package engine_test

import (
	"testing"

	"github.com/stretchr/testify/assert"

	engine "github.com/kickr-dev/engine/pkg"
)

func TestIsEmpty(t *testing.T) {
	cases := []struct {
		name    string
		content []byte
		policy  engine.EmptyPolicy
		kept    bool
	}{
		{"keep_policy_nil_content", nil, engine.PolicyKeep, false},
		{"keep_policy_with_content", []byte("package main"), engine.PolicyKeep, false},
		{"remove_nil_content", nil, engine.PolicyRemove, true},
		{"remove_empty_content", []byte{}, engine.PolicyRemove, true},
		{"remove_whitespace_only", []byte("  \n\t\n"), engine.PolicyRemove, true},
		{"remove_hash_notice", []byte("# Code generated by kickr; DO NOT EDIT.\n"), engine.PolicyRemove, true},
		{"remove_slash_notice", []byte("// Code generated by kickr; DO NOT EDIT.\n"), engine.PolicyRemove, true},
		{"remove_block_notice_single_line", []byte("/* Code generated by kickr; DO NOT EDIT. */\n"), engine.PolicyRemove, true},
		{"remove_html_notice", []byte("<!-- Code generated by kickr; DO NOT EDIT. -->\n"), engine.PolicyRemove, true},
		{"remove_multiline_block_notice", []byte("/*\nCode generated by kickr; DO NOT EDIT.\n*/\n"), engine.PolicyRemove, true},
		{"remove_multiline_html_notice", []byte("<!--\nCode generated by kickr; DO NOT EDIT.\n-->\n"), engine.PolicyRemove, true},
		{"remove_shebang_notice", []byte("#!/usr/bin/env bash\n# Code generated by kickr; DO NOT EDIT.\n"), engine.PolicyRemove, true},
		{"keep_shebang_with_content", []byte("#!/usr/bin/env bash\n# Code generated by kickr; DO NOT EDIT.\necho hi\n"), engine.PolicyRemove, false},
		{"remove_notice_second_line", []byte("\n# Code generated by kickr; DO NOT EDIT.\n"), engine.PolicyRemove, true},
		{"remove_notice_no_trailing_newline", []byte("# Code generated by kickr; DO NOT EDIT."), engine.PolicyRemove, true},
		{"keep_has_content_after_notice", []byte("// Code generated by kickr; DO NOT EDIT.\npackage main"), engine.PolicyRemove, false},
		{"keep_has_content_before_notice", []byte("package main\n// Code generated by kickr; DO NOT EDIT.\n"), engine.PolicyRemove, false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			// Act
			ok := engine.IsEmpty(tc.content, tc.policy)

			// Assert
			assert.Equal(t, tc.kept, ok)
		})
	}
}
