package engine

import (
	"bytes"
	"regexp"
)

var (
	delimiterOnlyLine = regexp.MustCompile(`(?m)^\s*(?:/\*|\*/|<!--|-->|#!.*)\s*$\n?`)
	generatedLine     = regexp.MustCompile(`(?m)^.*` + generated.String() + `.*$\n?`)
)

// EmptyPolicy defines the policy to apply when a generated file is empty.
//
// By default, the policy is set to PolicyRemove,
// meaning that a generated file will be removed if it is empty
// or contains only the notice "Code generated by [\w\-\/]+; DO NOT EDIT.".
type EmptyPolicy int

const (
	// PolicyKeep will keep the file if it exists and is empty.
	PolicyKeep EmptyPolicy = iota + 1

	// PolicyRemove will remove the file if it exists and is empty.
	//
	// This is the default behavior.
	PolicyRemove
)

// IsEmpty returns true if the given content is considered empty according to the provided policy.
//
// A file is expected to be removed if:
//   - it's empty
//   - it contains only the generated notice
//   - the policy is set to Keep
func IsEmpty(content []byte, policy EmptyPolicy) bool {
	if policy == PolicyKeep {
		return false
	}
	if len(content) == 0 {
		return true
	}
	return len(bytes.TrimSpace(delimiterOnlyLine.ReplaceAll(generatedLine.ReplaceAll(content, nil), nil))) == 0
}
