package engine

import (
	"bufio"
	"errors"
	"io"
	"io/fs"
	"os"
	"regexp"
)

// GeneratePolicy defines the policy for generating a given file.
//
// By default, the policy is set to PolicyNone,
// meaning that a given file will be generated if it doesn't exist, is empty
// or if the notice "Code generated by [\w\-\/]+; DO NOT EDIT." opens one of the first 3 lines.
type GeneratePolicy int

const (
	// PolicyAlways always generates the file.
	PolicyAlways GeneratePolicy = iota + 1

	// PolicyNone will generate the file using the default behavior.
	//
	// It means that a given file will be generated if it doesn't exist, is empty
	// or if the notice "Code generated by [\w\-\/]+; DO NOT EDIT." opens one of the first 3 lines.
	PolicyNone
)

const notice = `Code generated by [\w\-\/]+; DO NOT EDIT\.`

// generated matches the notice opening one of the first 3 lines, only comment syntax allowed before it.
var generated = regexp.MustCompile(`^(?:.*\n){0,2}[^\w\n]*` + notice)

// ShouldGenerate returns true if the file should be generated.
//
// A file is expected to be generated if:
//   - the generated notice opens one of its first 3 lines
//   - it does not exist
//   - it is empty
//   - the policy is set to PolicyAlways
func ShouldGenerate(out string, policy GeneratePolicy) (bool, error) {
	if policy == PolicyAlways || Forced() {
		return true, nil
	}

	file, err := os.Open(out)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return true, nil
		}
		return false, err
	}
	defer file.Close()

	// only the first 3 lines can hold the generated notice
	reader := bufio.NewReader(file)
	var head []byte
	for range 3 {
		line, err := reader.ReadBytes('\n')
		head = append(head, line...) // line is returned together with io.EOF in some cases
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return false, err
		}
	}
	return len(head) == 0 || generated.Match(head), nil
}
