package engine

import (
	"errors"
	"io/fs"
	"os"
	"regexp"
)

// GeneratePolicy defines the policy for generating a given file.
//
// By default, the policy is set to PolicyNone,
// meaning that a given file will be generated if it doesn't exist, is empty
// or if the notice "Code generated by [\w\-\/]+; DO NOT EDIT." is present.
type GeneratePolicy int

const (
	// PolicyAlways always generates the file.
	PolicyAlways GeneratePolicy = iota + 1

	// PolicyNone will generate the file using the default behavior.
	//
	// It means that a given file will be generated if it doesn't exist, is empty
	// or if the notice "Code generated by [\w\-\/]+; DO NOT EDIT." is present.
	PolicyNone
)

var generated = regexp.MustCompile(`Code generated by [\w\-\/]+; DO NOT EDIT.`)

// ShouldGenerate returns true if the file should be generated.
//
// A file is expected to be generated if:
//   - it contains the generated notice
//   - it does not exist
//   - it is empty
//   - the policy is set to PolicyAlways
func ShouldGenerate(out string, policy GeneratePolicy) (bool, error) {
	if policy == PolicyAlways || Forced() {
		return true, nil
	}

	content, err := os.ReadFile(out)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return true, nil
		}
		return false, err
	}

	// no reuse of IsEmpty: ShouldGenerate regenerates as soon as the notice appears anywhere in the file
	return len(content) == 0 || generated.Match(content), nil
}
